<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%
	th.co.exat.service.connectionJNDI jndi = new th.co.exat.service.connectionJNDI();

		String paramYear = request.getParameter("paramYear");
		//String paramYear = "2559";
		String query=
				" SELECT QQ.Num_C_Type, Round((Sum(Qq.C_P) / Totalb ) * 100 , 2), round((Sum(Qq.C_C) / Totaln ) * 100 , 2) FROM (SELECT Q.BUDDHIST_FISCAL_YEAR, Q.CUSTOMER_TYPE_CODE, Q.CUSTOMER_TYPE_NAME, Q.No_C_Type, Q.Num_C_Type,  '1' as joa, "+
						" CASE WHEN Q.CUSTOMER_TYPE_CODE = 'P' THEN COALESCE(SUM(Q.N_CUST_NAME),0) END AS C_P, CASE WHEN Q.CUSTOMER_TYPE_CODE = 'C' THEN COALESCE(SUM(Q.N_CUST_NAME),0) END AS C_C "+
						" FROM (SELECT  DD.BUDDHIST_FISCAL_YEAR, DCT.CUSTOMER_TYPE_CODE, DCT.CUSTOMER_TYPE_NAME, FCH.CUST_NAME, COALESCE(COUNT(FCH.CUST_NAME),0) AS N_CUST_NAME,  "+
						" CASE WHEN COUNT(FCH.CUST_NAME) = 1 THEN '1 บัตร' WHEN COUNT(FCH.CUST_NAME) BETWEEN 2 AND 5THEN '2-5 บัตร' When Count(Fch.Cust_Name) Between 6 And 10Then '6-10 บัตร' END AS Num_C_Type, "+
						" CASE WHEN COUNT(FCH.CUST_NAME) = 1 THEN '1' WHEN COUNT(FCH.CUST_NAME) BETWEEN 2 AND 5THEN '2'  When Count(Fch.Cust_Name) Between 6 And 10Then '3'  "+
						" END AS No_C_Type FROM FACT_CUST_HISTORY FCH, DIM_DATE DD,  DIM_CUSTOMER DC, DIM_CUSTOMER_TYPE DCT "+
						" WHERE FCH.TRANS_DATE_KEY = DD.DATE_KEY AND FCH.CUST_NO = DC.CUST_ID AND DC.CUST_TYPE = DCT.CUSTOMER_TYPE_CODE ANd DCT.CUSTOMER_TYPE_CODE NOT IN ('0','D','F') "+
						" AND (DD.BUDDHIST_FISCAL_YEAR = "+paramYear+") GROUP BY DD.BUDDHIST_FISCAL_YEAR, DCT.CUSTOMER_TYPE_CODE, DCT.CUSTOMER_TYPE_NAME, FCH.CUST_NAME)Q GROUP BY Q.BUDDHIST_FISCAL_YEAR, Q.CUSTOMER_TYPE_CODE, Q.CUSTOMER_TYPE_NAME, Q.No_C_Type, Q.Num_C_Type)Qq left join ( "+
						" Select  joc,Coalesce(Sum(Qq.C_P),0) As TotalB,Coalesce(Sum(Qq.C_C),0) As totalN FROM (SELECT Q.BUDDHIST_FISCAL_YEAR, Q.CUSTOMER_TYPE_CODE, Q.CUSTOMER_TYPE_NAME, Q.No_C_Type, Q.Num_C_Type, '1' as joc, "+
						" CASE WHEN Q.CUSTOMER_TYPE_CODE = 'P' THEN COALESCE(SUM(Q.N_CUST_NAME),0) END AS C_P, CASE WHEN Q.CUSTOMER_TYPE_CODE = 'C' THEN COALESCE(SUM(Q.N_CUST_NAME),0) END AS C_C FROM (SELECT  DD.BUDDHIST_FISCAL_YEAR,  DCT.CUSTOMER_TYPE_CODE,  DCT.CUSTOMER_TYPE_NAME, "+
						" FCH.CUST_NAME, COALESCE(COUNT(FCH.CUST_NAME),0) AS N_CUST_NAME,  CASE WHEN COUNT(FCH.CUST_NAME) = 1 THEN '1 บัตร' WHEN COUNT(FCH.CUST_NAME) BETWEEN 2 AND 5THEN '2-5 บัตร' When Count(Fch.Cust_Name) Between 6 And 10Then '6-10 บัตร' END AS Num_C_Type, "+
						" CASE WHEN COUNT(FCH.CUST_NAME) = 1 THEN '1' WHEN COUNT(FCH.CUST_NAME) BETWEEN 2 AND 5THEN '2' When Count(Fch.Cust_Name) Between 6 And 10Then '3' END AS No_C_Type "+
						" FROM  FACT_CUST_HISTORY FCH, DIM_DATE DD, DIM_CUSTOMER DC,  DIM_CUSTOMER_TYPE DCT WHERE FCH.TRANS_DATE_KEY = DD.DATE_KEY AND FCH.CUST_NO = DC.CUST_ID AND DC.CUST_TYPE = DCT.CUSTOMER_TYPE_CODE ANd DCT.CUSTOMER_TYPE_CODE NOT IN ('0','D','F') "+
						" AND (DD.BUDDHIST_FISCAL_YEAR = "+paramYear+") GROUP BY DD.BUDDHIST_FISCAL_YEAR, DCT.CUSTOMER_TYPE_CODE, DCT.CUSTOMER_TYPE_NAME,  FCH.CUST_NAME)Q   "+
						" where No_C_Type is not null GROUP BY Q.BUDDHIST_FISCAL_YEAR, Q.CUSTOMER_TYPE_CODE, Q.CUSTOMER_TYPE_NAME, Q.No_C_Type, Q.Num_C_Type)Qq group by joc )Qq2 on Qq2.joc = Qq.joa "+
						" where No_C_Type is not null Group By Qq.No_C_Type,Qq.Num_C_Type,Joa,Totalb,totalN ORDER BY QQ.No_C_Type ";
		String columns="1,2,3";
		
		
	jndi.selectByIndexDwh(query, columns);
	out.println(jndi.getData());
    
%>